function [ch]=CHAN_createNewChannel()
    ch = mlist(["chan","z","Pref","iin","Dh","Ph","Axs","q2p","G","iz","grav","rgh", ...
     "Loss","VF_opt","Cf_opt","Fi2_opt","Fi2l_opt","Dpz","Dpz_grav", "Dpz_fric", "Dpz_acc", "Dpz_loc", "vf","xa","xe"], ...
      [],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]);
endfunction
